trigger:
  branches:
    include:
      - master
      - rel/*

pr:
  branches:
    include:
      - master
      - rel/*

pool:
  vmImage: windows-latest

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  
- script: nbgv cloud
  displayName: Set Version

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: Membership/Membership.csproj
    arguments: '-c $(BuildConfiguration) --output $(build.artifactstagingdirectory)\website\'
    zipAfterPublish: True

- publish: $(Build.ArtifactStagingDirectory)\website
  displayName: Publish website artifact
  artifact: Website
